### ISSUE TITLE
Latest build missing Ruby 3.3.0

### ISSUE THREAD

**Issue by maxlapides** [cirruslabs/macos-image-templates#112]
For some reason, the latest build of the macos runners seems to be missing Ruby 3.3.0. Running `brew update && brew upgrade && rbenv install 3.3.0 --skip-existing` does fix the issue, but it takes a minute.

**Comment by fkorotkov** [comment]
@maxlapides I see that the latest `ghcr.io/cirruslabs/macos-sonoma-base:latest` has `3.2.2` installed. Where do you see it missing?

**Comment by maxlapides** [comment]
Oh I see, Ruby 3.3.0 is actually a new release as of a couple days ago. Didn't realize we had automatically upgraded from 3.2.2.

**Comment by fkorotkov** [comment]
We rebuild base variant of the image monthly on the first Saturday of a month. On January 6th it will pick up the latest ruby version there is.

**Comment by maxlapides** [comment]
Thank you!
