### ISSUE TITLE
Add macos-ventura-vanilla:13.6.2 image

### ISSUE THREAD

**Issue by EthisDF** [cirruslabs/macos-image-templates#114]
Hello, 

Is it possible to add macos-ventura-vanilla:13.6.2 image for virtual machine please ? 

Thank you a lot !

**Comment by fkorotkov** [comment]
[Doesn't see there is an IPSW for `13.6.2`](https://ipsw.me/VirtualMac2,1). Only for `13.6`. Will that work for you?

**Comment by EthisDF** [comment]
That's perfect, thank you so much !

**Comment by fkorotkov** [comment]
13.6 is now available
