### ISSUE TITLE
flutter-less xcode image?

### ISSUE THREAD

**Issue by umlaeute** [cirruslabs/macos-image-templates#115]
i wonder if you would consider providing images that only have `brew`+`XCode`, but no ~~`flutter`, `android-sdk`~~ and the like.

As of now, i need to uninstall a couple of packages first in order to be able to use `brew`:

```
brew uninstall -f android-ndk android-sdk temurin8 libimobiledevice ideviceinstaller ios-deploy fastlane libusb libusbmuxd
```

my understanding is, that this is because i'm using the monterey images (`ghcr.io/cirruslabs/macos-monterey-xcode:latest`): these images are no longer updated (by you), but come with a an outdated (by new) `brew` installation that fails on the formula of one or another of the installed packages.

the lesson i learned from this is, that the more dependencies are pre-installed, the more can go stale and break things.

(otoh, i do want `XCode` pre-installed, as it is huge; and a basic `brew` installation is also very welcome)

**Comment by fkorotkov** [comment]
We are trying to keep the VM image as lean as possible but not planning to remove Flutter or have a separate variant. There is too much historical reasons.

**Comment by umlaeute** [comment]
fair enough.


so how can I use `brew` on `macos-monterey-xcode:latest`?
and if that ship has sailed, are there any plans for future images to not fall into the same trap?
