### ISSUE TITLE
Any recommendation on how to execute the GitHub actions runner?

### ISSUE THREAD

**Issue by plu** [cirruslabs/macos-image-templates#118]
First of all: Thank you for creating and maintaining these templates, it's a joy to work with them.

To automatically start the runner as a service I've created another template that simply does a `actions-runner/svc.sh install`. You can see the full template [here](https://github.com/plu/macos-image-templates/commit/633d9f13e0d3d09b0c7176fb23a6ff5c6c3adb8f#diff-79ca12ecb925f6eb7977df03b9a68546b51c64cb09af149890389bc52276edfeR38). Starting it via launchd comes with some downsides, it does not have the same shell environment like the admin user when running an interactive shell in the Terminal.app. So for example `PATH` looks different, among other things. I figured you can [set the path](https://github.com/plu/macos-image-templates/commit/90f9a2a4786889cd65da5f1545f3cd341cad0464#diff-79ca12ecb925f6eb7977df03b9a68546b51c64cb09af149890389bc52276edfeR38) via some special file. But in the end I was just wondering: How do you guys usually launch the runner? Do you ssh into the VM and just launch it from that session?

**Comment by fkorotkov** [comment]
Embedding secrets like registration token within your VM is a bad practice and we won't recommend doing so. Access to the VM will give up your secrets.

For [Cirrus Runners](https://cirrus-runners.app/) we have automation that boots a VM, SSHs into it and runs the GHA scripts to start an `--ephemeral` runner, waits for the completion, deletes the VM and repeats.

**Comment by plu** [comment]
Thank you for your answer. I'm aware of the risk, my use case is only for private repositories in a trusted environment. I was just wondering how you achieve to have the `admin`'s environment loaded when executing the runner. Feel free to close the issue as I have the answer now: Using ssh. Thank you again :).
