### ISSUE TITLE
xcodes usage

### ISSUE THREAD

**Issue by umlaeute** [cirruslabs/macos-image-templates#122]
i was about to report that the Xcode-download is broken, only to notice that you just submitted #121 :-)
then i was about to ask why manually download `xcodes` rather than doing a `brew install xcodes`, only to discover that this is also addressed in #121. sigh.

so finally here's two suggestions (hopefully not yet implemented!)

- `xcodes` as a `--select` option that makes https://github.com/cirruslabs/macos-image-templates/blob/002717156a2e4d1f11593c364d964b90fe2b4733/templates/xcode.pkr.hcl#L86 obsolete
- `xcodes` moves the .XIP file into Trash, so https://github.com/cirruslabs/macos-image-templates/blob/002717156a2e4d1f11593c364d964b90fe2b4733/templates/xcode.pkr.hcl#L85 is redundant
- `xcodes` has a `--empty-trash` option, making https://github.com/cirruslabs/macos-image-templates/blob/002717156a2e4d1f11593c364d964b90fe2b4733/templates/xcode.pkr.hcl#L84 obsolete.

so I'd like to suggest to use this:

```diff
diff --git a/templates/xcode.pkr.hcl b/templates/xcode.pkr.hcl
index d6d7cde..6227b90 100644
--- a/templates/xcode.pkr.hcl
+++ b/templates/xcode.pkr.hcl
@@ -80,10 +80,7 @@ build {
       "source ~/.zprofile",
       "brew install xcodesorg/made/xcodes",
       "xcodes version",
-      "xcodes install ${var.xcode_version} --experimental-unxip --path /Users/admin/Downloads/Xcode_${var.xcode_version}.xip",
-      "sudo rm -rf ~/.Trash/*",
-      "sudo rm -rf ~/Downloads/*",
-      "xcodes select ${var.xcode_version}",
+      "xcodes install ${var.xcode_version} --experimental-unxip --path /Users/admin/Downloads/Xcode_${var.xcode_version}.xip --select --empty-trash",
       "xcodebuild -downloadAllPlatforms",
       "xcodebuild -runFirstLaunch",
     ]
```

**Comment by fkorotkov** [comment]
Thank you for the info! Yeah, we can open a PR and apply your suggesting or if you want to be on the list of contributors, feel free to submit a PR yourself!
