### ISSUE TITLE
Outdated variants?

### ISSUE THREAD

**Issue by ruimarinho** [cirruslabs/macos-image-templates#128]
Hi,

As per a comment on a previous issue, images should be getting updates on the first Saturday of each month. However, looking at the PR that introduced the dynamic github actions runner fetcher, it seems like at least `ghcr.io/cirruslabs/macos-sonoma-xcode:15.1` has not been updated to reflect that change.

Is this schedule still applicable? 

Many thanks 🙏

**Comment by ruimarinho** [comment]
You guys are amazing! Thank you so much!

**Comment by fkorotkov** [comment]
For the next version of macOS we'll probably switch to an omni variant with several latest Xcode versions. Which we'll update even more frequently. 👌

**Comment by ruimarinho** [comment]
@fkorotkov is the same cron schedule maintained with the current release setup? First Saturday of each month?

**Comment by fkorotkov** [comment]
Yes, waiting for 5am EST tomorrow myself to see how it goes and fix things if needed.

**Comment by ruimarinho** [comment]
Good morning! Looks like https://github.com/cirruslabs/macos-image-templates/pkgs/container/macos-sonoma-xcode is still not updated with the latest changes.

**Comment by fkorotkov** [comment]
Morning! My bad. The cron jos is scheduled at 7am EST every first Saturday of a month. Next invocation should be in 35 minutes and should appear [here](https://cirrus-ci.com/github/cirruslabs/macos-image-templates). Build will take an hour or so though.

**Comment by fkorotkov** [comment]
Didn't work because of a silly typo. Changed from to 9am which will retry in 25 minutes

**Comment by ruimarinho** [comment]
Indeed - the second run worked great! Thank you!
