### ISSUE TITLE
Slow pulling

### ISSUE THREAD

**Issue by gluefox** [cirruslabs/macos-image-templates#151]
I am experiencing very slow download speeds from the registry running tart clone. After an initial phase of ~1min with good download speeds, the traffic drops to 1MB/s. I am seeing this on two machines in different regions (one local, one cloud).

Any help is appreciated.

**Comment by fkorotkov** [comment]
What kind of registry do you use?

**Comment by gluefox** [comment]
The github registry.

`tart clone ghcr.io/cirruslabs/macos-runner:sonoma macos-runner`

**Comment by fkorotkov** [comment]
Which version of Tart and macOS do you use? I can't reproduce on Tart 2.10.0 and macOS 14.4.1. Getting a stable 800-900 Mbps from two separate locations.

**Comment by gluefox** [comment]
I am on Ventura 13.5.2 with tart 2.10.0. Might as well be an internet problem since I am seeing slower speeds on other brew installs as well (https://downdetector.com/status/github/).

**Comment by fkorotkov** [comment]
Seems so. Closing then.
