### ISSUE TITLE
[Question] Why enable Voice Over in vanilla packer templates?

### ISSUE THREAD

**Issue by hisaac** [cirruslabs/macos-image-templates#173]
I see in your vanilla packer templates, after you get past the initial setup screens and can see the desktop, you enable Voice Over

https://github.com/cirruslabs/macos-image-templates/blob/525f51a54e53036cd6bfdb0b28bfa35a49dd303c/templates/vanilla-sequoia.pkr.hcl#L66-L67

and then disable it again a few lines later

https://github.com/cirruslabs/macos-image-templates/blob/525f51a54e53036cd6bfdb0b28bfa35a49dd303c/templates/vanilla-sequoia.pkr.hcl#L76-L77

Just out of curiosity, what's the need for those steps?

**Comment by hisaac** [comment]
Never mind, I get it now! It's so that you can navigate the UI of the System Preferences window via the keyboard. Clever!

**Comment by hisaac** [comment]
Hey @fkorotkov I reopened this and deleted my previous comment because I actually still don't know why Voice Over is enabled. I thought initially it was to navigate System Preferences with the keyboard, but that's not actually necessary it seems. Any insight you can provide?

**Comment by fkorotkov** [comment]
It's to emable Remote Sharing so VM is SSHable:

https://github.com/cirruslabs/macos-image-templates/blob/525f51a54e53036cd6bfdb0b28bfa35a49dd303c/templates/vanilla-sequoia.pkr.hcl#L66-L77

But the voice over it getting disabled in the end so you should not see it.
