### ISSUE TITLE
Unable to clone or pull macOS Sequoia images with Xcode

### ISSUE THREAD

**Issue by tonyarnold** [cirruslabs/macos-image-templates#180]
Hi folks, I'm unable to pull the latest macOS Sequoia with Xcode images as documented on https://github.com/cirruslabs/macos-image-templates/pkgs/container/macos-runner

```sh
❯ tart pull ghcr.io/cirruslabs/macos-sequoia-xcode
pulling ghcr.io/cirruslabs/macos-sequoia-xcode:latest...
pulling manifest...
Error: AuthFailed(why: "received unexpected HTTP status code 403 while retrieving an authentication token", details: "{\"errors\":[{\"code\":\"DENIED\",\"message\":\"requested access to the resource is denied\"}]}\n")
```

Am I doing something wrong?

**Comment by fkorotkov** [comment]
Hi! We haven't yet started building Sequoia Xcode images. Please use Sonoma ones or build them yourself.

PS we'll probably start building them next week when Sequoia is released.

**Comment by tonyarnold** [comment]
Thanks, @fkorotkov! I can totally wait - thanks for letting me know about where things are at 😄
