### ISSUE TITLE
New Xcode 16 RC version

### ISSUE THREAD

**Issue by kondratk** [cirruslabs/macos-image-templates#181]
Hey!
Apparently apple did release another version of Xcode 16.0 disallowing previous RC from being used to upload apps.

Can we please have the Xcode 16 image re-built with latest 16.0? 🙏🏻 

```
Asset validation failed Unsupported SDK or Xcode version. Your app was built with an SDK or version of Xcode that isn’t supported. Although you can use beta versions of SDKs and Xcode to build and upload apps to App Store Connect, you need to use the latest Release Candidates (RC) for SDKs and Xcode to submit the app.
```

**Comment by fkorotkov** [comment]
`ghcr.io/cirruslabs/macos-sonoma-xcode{:16,:latest}` has been just updated and a new `ghcr.io/cirruslabs/macos-runner:sonoma` for [Cirrus Runners](https://cirrus-runners.app/) will be rolled out in the next couple of hours.
