### ISSUE TITLE
Pre-warmed macos-runner:sequoia runner

### ISSUE THREAD

**Issue by maxlapides** [cirruslabs/macos-image-templates#183]
Hi @fkorotkov, I was wondering if you have a plan to create a `ghcr.io/cirruslabs/macos-runner:sequoia` image? Thank you!

**Comment by fkorotkov** [comment]
Plan for this weekend. Then in couple of weeks make it the pre-warmed one.

**Comment by maxlapides** [comment]
The Sequoia runner is working well, thank you!
