### ISSUE TITLE
Network issues with macOS VMs?

### ISSUE THREAD

**Issue by real-or-random** [cirruslabs/macos-image-templates#42]
We're recently seeing some aborted downloads:

https://cirrus-ci.com/task/4833814164799488?logs=clone#L283
https://cirrus-ci.com/task/4974551653154816?logs=brew#L67
https://cirrus-ci.com/task/5453152945176576?logs=brew_valgrind_pre#L5701 (not sure here, this one just stalled forever?!)

Maybe it was just a hiccup but I thought it's a good idea to let you know.

**Comment by real-or-random** [comment]
Here's recent one: https://cirrus-ci.com/task/5997748104200192

**Comment by fkorotkov** [comment]
Sorry I just saw the issue. It seems very suspicions that around both times there were GitHub incidents:

- [Dec 27, 2021](https://www.githubstatus.com/incidents/gh0vvxtlj5v7) - exactly around the time you saw the issues.
- [Jan 27, 2022](https://www.githubstatus.com/incidents/29xnrws671f0) - not particularly at the same time the incident got reported but pretty close. GitHub tends to acknowledge incidents when it's too far to ignore.

Both issues looks like GitHub related. Let's continue keeping an eye on it.
