### ISSUE TITLE
Missing Git LFS

### ISSUE THREAD

**Issue by maxlapides** [cirruslabs/macos-image-templates#62]
Hi there! I'm testing out Cirrus Runners for our iOS build! It would be great if Git LFS came installed on the runners. Thank you!

**Comment by fkorotkov** [comment]
Added in [ea5b92a](https://github.com/cirruslabs/macos-image-templates/commit/ea5b92acd84f2b70e715d003518e9c396c238889). Which image are you testing? `macos-ventura-xcode:latest` or just the base one?

**Comment by maxlapides** [comment]
Nice thanks! Yep I’m using `macos-ventura-xcode:latest`

**Comment by maxlapides** [comment]
@fkorotkov I think we will also need to add `git lfs install` to complete the Git LFS installation. (This instruction is printed by brew install.)

**Comment by fkorotkov** [comment]
Good catch! Thanks for the quickest response. I haven't even initialized a rebuild of the images but will do shortly. I'll close the issue once updated VMs are pushed.

**Comment by maxlapides** [comment]
Amazing, thanks so much! And while you're working on this, I opened another similar issue for your consideration: https://github.com/cirruslabs/macos-image-templates/issues/63 😁

**Comment by fkorotkov** [comment]
It's got deployed!
