### ISSUE TITLE
Add jq to macos-ventura-xcode

### ISSUE THREAD

**Issue by maxlapides** [cirruslabs/macos-image-templates#63]
I'm using [subosito/flutter-action](https://github.com/subosito/flutter-action) to install the correct version of Flutter. It works well with `macos-ventura-xcode` except we need to `brew install jq`. Can we also add `jq` to the xcode image?

**Comment by fkorotkov** [comment]
Fixed in dd53dd75566ff8b6e83901affc5649f9f1f1ddca and updated ventura 14.1 got pushed already.
