### ISSUE TITLE
M1 based macOS between 2-3x slower than the Intel

### ISSUE THREAD

**Issue by ibuclaw** [cirruslabs/macos-image-templates#66]
Example of before and after:
https://cirrus-ci.com/task/4541429968535552
![image](https://user-images.githubusercontent.com/397929/210243646-d83fd332-c421-4602-92d3-00deb637646c.png)

https://cirrus-ci.com/task/5354105359564800
![image](https://user-images.githubusercontent.com/397929/210244505-9339201a-0f8c-4796-b42b-3827e648d936.png)

This is going to hurt during the occasional peaks coming from PRs raised by our many contributors, especially as there's on only one instance allowed to run across the three repositories using the macOS runners in our GH organization.

---

I had a look into getting possible funding to switch to a paid plan, but of the options available, none of them actually fit us.  We are neither a private personal, nor a private organization.  Rather, a not-for-profit public organization maintaining open-source projects - perhaps the wording of the plan descriptions is terrible?
![image](https://user-images.githubusercontent.com/397929/210244836-b31f9816-ab17-4c6b-ab6f-1c0b3a9b8677.png)

**Comment by fkorotkov** [comment]
Could it be that you run still running x86 binaries under Rosetta? [This log line looks a bit suspicious](https://cirrus-ci.com/task/5354105359564800?logs=test_dmd#L18).

**Comment by ibuclaw** [comment]
> Could it be that you still running x86 binaries under Rosetta? [This log line looks a bit suspicious](https://cirrus-ci.com/task/5354105359564800?logs=test_dmd#L18).

Yes, the reference D compiler has no ARM backend - sadly, unfortunately, _sigh_. :-)

**Comment by fkorotkov** [comment]
That might explain the slowness. 😪 Even though the M1 instances has 4 cores instead of 6 cores with hyper-threading like the old Intel instance, we only saw performance improvements thought out our users.

As per the options, it seems there are three of them:

1. Support Arm backend. But it might be too much to ask. 😅
2. Use [compute credits](https://cirrus-ci.org/pricing/#compute-credits) to increase parallelism for `master` branch.
3. If you happen to have Intel Macs at you disposal, you can configure them as [persistent workers](https://cirrus-ci.org/guide/persistent-workers/).

On a side note. At the moment Cirrus CI's parallelism limits are enforced on per-user basis and not on per-organization so each contributor has one instance to run PRs on.

**Comment by ibuclaw** [comment]
> That might explain the slowness. sleepy Even though the M1 instances has 4 cores instead of 6 cores with hyper-threading like the old Intel instance, we only saw performance improvements thought out our users.

OK. Is it possible that the FAQs are still out of date?

https://cirrus-ci.org/faq/#are-there-any-limits

> As per the options, it seems there are three of them:
> 
>     1. Support Arm backend. But it might be too much to ask. sweat_smile
> 

Given that there are both GCC and LLVM backed D compilers, I see two chances of updating the Zortech/DigitalMars back-end to spew out ARM object code - fat and slim. :-)

>     2. Use [compute credits](https://cirrus-ci.org/pricing/#compute-credits) to increase parallelism for `master` branch.
> 

How many CPUs are used if compute credits are available? It's not too clear from the documentation, compared to, say the Linux docs, where it says you can tune CPU requirements as-needed in the config, e.g:
```
linux_task:
  name: Ubuntu 22.04
  container:
    image: ubuntu:22.04
    cpu: 4
    memory: 8G
```
The FAQs say the macOS VMs are not configurable.

> On a side note. At the moment Cirrus CI's parallelism limits are enforced on per-user basis and not on per-organization so each contributor has one instance to run PRs on.

That's good to know.  So when I am having to update all three repositories simultaneously, the long wait for all pipelines to finish is just me. :-)
