### ISSUE TITLE
Images timezone defaulted to PDT

### ISSUE THREAD

**Issue by dniHze** [cirruslabs/macos-image-templates#67]
Currently, the image timezone defaults to PDT(GMT-8). This might come as unexpected details for some people or in some setups. Given it might be wrong or difficult for tart to set the timezone of the host machine to the VM, it might be worth setting the default image timezone to GMT.

**Comment by fkorotkov** [comment]
Hey @dniHze, this is the default location/timezone Apple set for macOS. Unfortunately location services are not working from within the virtual machine and therefore it can't automatically pick your timezone.  Created https://github.com/cirruslabs/tart/issues/373 to track the issue.
