### ISSUE TITLE
Pre-download some iOS/watchOS/iPadOS major releases to XCode images 

### ISSUE THREAD

**Issue by dniHze** [cirruslabs/macos-image-templates#68]
Each XCode bundles only the latest iOS/watchOS/iPadOS "platforms". For example, XCode 14.0.1 bundles iOS 16.0, while 14.1 only bundles 16.1. While for some teams it might be a pretty minor change, the inability to target the same platform when switching XCode versions without pipeline changes might be a large friction point.

Also, while we don't, some teams run tests on multiple older versions to verify compatibility. Not bundling platforms images probably save a lot of space, but it adds overhead when you need them, so you either should do pre-setup chores or check for platforms inside the image, which leads to longer pipeline runs.

I don't have a particularly good policy in my mind for this problem, but I think voicing it and bringing the discussion to this might be reasonable.

**Comment by fkorotkov** [comment]
Just couple of clarification question. Do you use the images via Cirrus CI, Cirrus Runners or your own infrastructure?

I guess the best start will be to pre-download only previous iOS and watch platforms. Platforms are pretty hefty to download all of them.

**Comment by fkorotkov** [comment]
Closing since haven't had a response.
