### ISSUE TITLE
Shorten the initial startup time of macOS vm.

### ISSUE THREAD

**Issue by mafreud** [cirruslabs/macos-image-templates#70]
First, thank you for your great products!

I am currently building a CI/CD with tart, using packer build to create vm images, but the initial setup of macOS (language selection ~ agreement) takes a long time. Also, not everything is done automatically and sometimes it stops in the middle.

So I thought to save the vm image that finished the initial setup in the registry (ghcr.io) and tart pull, but it seems that the state is not saved.

Is there any solution?

Also, I am thinking that the vm environment should be destroyed after each CI/CD build, but maybe I am wrong here. What do you think?

**Comment by fkorotkov** [comment]
If you finish the initial setup, shutdown the vm and push it, the state should be persisted. This is what we do for [Cirrus CI's `macos_instance`](https://cirrus-ci.org/guide/macOS/).

**Comment by mafreud** [comment]
@fkorotkov OK, I will try. Thank you so much!
