### ISSUE TITLE
can not build maos 12 wheels

### ISSUE THREAD

**Issue by xunonxyz** [cirruslabs/macos-image-templates#80]
need support for macos 12

**Comment by fkorotkov** [comment]
You can still find [`macos-monterey-` images](https://github.com/orgs/cirruslabs/packages?tab=packages&q=macos-monterey) and even build it if you change or override [`macos_version` variable](https://github.com/cirruslabs/macos-image-templates/blob/master/variables.pkrvars.hcl#LL1C9-L1C9).
