### ISSUE TITLE
Upgrade to Ventura 13.4

### ISSUE THREAD

**Issue by amontoison** [cirruslabs/macos-image-templates#84]
Is it possible to upgrade the version of MacOS Ventura to 13.3 or higher?
With Ventura 13.3, Apple dded a new version of BLAS and LAPACK after more than 10 years without any update.
It will very useful for project related to high performance computing.

Thanks a lot for helping us to test our code on the new Apple M1!

**Comment by fkorotkov** [comment]
Which version of the image are you referering to? The base Ventura image should be [based of `13.3.1`](https://github.com/cirruslabs/macos-image-templates/blob/42b40752b5590aaa700f6b5e166c9d81cb4ddadb/templates/base.pkr.hcl#L19) and we certainly will push `13.4` base image this week.

**Comment by amontoison** [comment]
I thought that the version 13.1 was used.
I found the culprit. I forgot to use a specific flag to compile with the new BLAS and LAPACK libraries.
It solves my issue with the version `13.3.1`.
