### ISSUE TITLE
Resize "the disk" of an existing image?

### ISSUE THREAD

**Issue by grigorye** [cirruslabs/macos-image-templates#86]
I wonder if it's possible to adjust the disk size of an VM, e.g. on cloning (leaving aside, stopped image). I am in a situation where I use prebuilt VMs built from https://github.com/cirruslabs/macos-image-templates, but I eventually lack disk space.

While I *can* build a custom image with packer and etc. to accommodate the needs (thanks for open-sourcing these templates as well), I would prefer not to do it, rather just "adjust the size disk in VM", if possible... It could also help when iterating on something without realizing how much space would you need in VM.

**Comment by fkorotkov** [comment]
Yes, you can replicate [`disk_size_gb`](https://github.com/cirruslabs/macos-image-templates/blob/62bb71fc2ce4a0c974815e8574a8f15a25a97149/templates/xcode.pkr.hcl#L32) behaviour by replicating [logic from the plugin](https://github.com/cirruslabs/packer-plugin-tart/blob/9ddd019ddc45e851a734e0b8da83adc786fcfd65/builder/tart/step_disk_resize.go#L14).

Please refer to @qbx2 answer here: https://github.com/cirruslabs/tart/issues/17#issuecomment-1439367869
