### ISSUE TITLE
sonoma-vanilla Package is outdated

### ISSUE THREAD

**Issue by melgu** [cirruslabs/macos-image-templates#92]
The `sonoma-vanilla` package is outdated. I've opened two PRs in the last days to update the macOS 14 Beta. Those have been merged, but the package [here](https://github.com/cirruslabs/macos-image-templates/pkgs/container/macos-sonoma-vanilla) is still an older version.

Do I or you need to to anything else?

**Comment by fkorotkov** [comment]
Pushing vanilla images is a manual process at the moment because the setup sometimes flake and we do a quick manual verification before pushing. Just pushed the Beta 3.
