### ISSUE TITLE
Image update schedule

### ISSUE THREAD

**Issue by ruimarinho** [cirruslabs/macos-image-templates#93]
Hi,

Do you plan on enabling a build-on-push strategy or is there some other process for updates images on the github registry?

Looking forward to see the updated github actions runner version pushed as disabling gha auto updates crashes the runner at the moment :)

Thanks!

**Comment by fkorotkov** [comment]
The base image is [updated automatically on the first Saturday of the month](https://github.com/cirruslabs/macos-image-templates/blob/4e75d95247581586a42dae1d52669ddbaa014898/.cirrus.yml#L2-L3). Deploying off pick hours allow to slowly populate local caches of the workers over the weekend.

Regarding the Xcode variant, it is updated manually upon a release in this repository. I just cut `15-beta-5` release which will contain the new version but it won't be tagged as `latest`.

On a side note. For [Cirrus Runners](https://tart.run/integrations/github-actions/) we found that disabling auto-update is not working as expected. To our knowledge there is no public knowledge about when a particular runner version will stop working.

**Comment by ruimarinho** [comment]
Thanks @fkorotkov -- shouldn't https://github.com/cirruslabs/macos-image-templates/pkgs/container/macos-ventura-xcode/101275224?tag=14.3.1 have been updated yesterday with the [newest version of GitHub Runners](https://github.com/cirruslabs/macos-image-templates/commit/4e75d95247581586a42dae1d52669ddbaa014898)?

**Comment by fkorotkov** [comment]
Unfortunately, no. Only the base was updated during the cron. Fixing it in #94.

In the meantime I've manually re-ran the task that rebuilt `14.3.1`.

**Comment by ruimarinho** [comment]
@fkorotkov it seems like `ghcr.io/cirruslabs/macos-ventura-xcode:14.3.1` is still shipping with `2.303.0`. Do you confirm this as well?
