### ISSUE TITLE
nvm missing from ghcr.io/cirruslabs/macos-ventura-xcode

### ISSUE THREAD

**Issue by macrozone** [cirruslabs/macos-image-templates#95]
hi, i am new to tart.

i tried the ghcr.io/cirruslabs/macos-ventura-xcode and based on the git history of this repo here, nvm should be installed, but its not available. any hint to fix this?

**Comment by fkorotkov** [comment]
Yes, we opted out for just installing the latest node via brew. `nvm`'s way of having things in environment variable didn't play nicely with the way GitHub Actions Runner executes builds.

**Comment by macrozone** [comment]
@fkorotkov thanks for your explanation.

what is the simplest way to create an image based on `ghcr.io/cirruslabs/macos-ventura-xcode` with nvm included?

i saw packer, but that seems a bit more sophisticated. is it also possible to start tart with an image, do some changes on it and then snapshot it to a new image?

**Comment by fkorotkov** [comment]
Yes, you can start a local image cloned from `ghcr.io/cirruslabs/macos-ventura-xcode:latest`, do some manual changes that will be persisted upon shutting down the VM.

Then you either need to push this modified image if you want to distribute it to other hosts or you can use this modified local image for creating more clones on this host to run your ephemeral tasks.

**Comment by macrozone** [comment]
> Yes, you can start a local image cloned from `ghcr.io/cirruslabs/macos-ventura-xcode:latest`, do some manual changes that will be persisted upon shutting down the VM.
> 
> Then you either need to push this modified image if you want to distribute it to other hosts or you can use this modified local image for creating more clones on this host to run your ephemeral tasks.

thank you!
