### ISSUE TITLE
CocoaPods 1.13.0

### ISSUE THREAD

**Issue by maxlapides** [cirruslabs/macos-image-templates#99]
Hey @fkorotkov, could we please update the Sonoma runners with CocoaPods 1.13.0? There are some crucial fixes in there for Flutter apps. Thank you!

**Comment by fkorotkov** [comment]
[Re-ran](https://cirrus-ci.com/task/6585726347771904) the task to release it. Should be available in 30ish minutes.

**Comment by maxlapides** [comment]
Oh @fkorotkov could you please check on that deploy? I think it may have failed.

**Comment by fkorotkov** [comment]
Should be up now 👌
